services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db  
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/app_db
      INTERNAL_API_BASE_URL: http://nginx/api/v1
      INTERNAL_API_TOKEN: dev-internal-token
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  backend-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db  
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/app_db
      INTERNAL_API_BASE_URL: http://nginx/api/v1
      INTERNAL_API_TOKEN: dev-internal-token
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend-1
      - backend-2

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  outbox-consumer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -m app.application.outbox_consumer
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/app_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    restart: unless-stopped


volumes:
    postgres_data:
