"""add retry fields to jobs

Revision ID: 22c62bf6f97c
Revises: 91c79067aa44
Create Date: 2026-03-28 14:12:16.015584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '22c62bf6f97c'
down_revision: Union[str, Sequence[str], None] = '91c79067aa44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("max_retries", sa.Integer(), nullable=True))
    op.add_column("jobs", sa.Column("next_run_at", sa.DateTime(), nullable=True))

    op.execute("UPDATE jobs SET max_retries = 3 WHERE max_retries IS NULL")
    op.execute("UPDATE jobs SET next_run_at = NOW() WHERE next_run_at IS NULL")

    op.alter_column("jobs", "max_retries", nullable=False)
    op.alter_column("jobs", "next_run_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "next_run_at")
    op.drop_column("jobs", "max_retries")
    # ### end Alembic commands ###
