"""add retry fields to jobs v-2

Revision ID: 58cb85b776e9
Revises: 22c62bf6f97c
Create Date: 2026-03-28 16:24:54.406310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58cb85b776e9'
down_revision: Union[str, Sequence[str], None] = '22c62bf6f97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("jobs", "retries", new_column_name="retry_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("jobs", "retry_count", new_column_name="retries")
    # ### end Alembic commands ###
