"""add indexes

Revision ID: aa4befd742a7
Revises: a1d1f279c0fa
Create Date: 2026-05-09 16:20:14.996379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4befd742a7'
down_revision: Union[str, Sequence[str], None] = 'a1d1f279c0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_borrow_records_book_id'), 'borrow_records', ['book_id'], unique=False)
    op.create_index(op.f('ix_borrow_records_user_id'), 'borrow_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_borrow_records_user_id'), table_name='borrow_records')
    op.drop_index(op.f('ix_borrow_records_book_id'), table_name='borrow_records')
    # ### end Alembic commands ###
