"""add category_id to books

Revision ID: b4ed959db82f
Revises: d73f480d556e
Create Date: 2026-03-08 14:40:12.993329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ed959db82f'
down_revision: Union[str, Sequence[str], None] = 'd73f480d556e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_index(
        op.f('ix_books_category_id'),
        'books',
        ['category_id'],
        unique=False
        )
    op.create_foreign_key(None, 'books', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_category_id'), table_name='books')
    op.drop_column('books', 'category_id')
    # ### end Alembic commands ###
